language: python
python:
  - "2.7"
  - "3.6"
#  - "3.6-dev" # 3.6 development branch
#  - "3.7-dev" # 3.7 development branch
#  - "nightly" # currently points to 3.7-dev
# command to install Ubuntu packages before installing
before_install:
  - sudo apt-get update -qq
# command to install dependencies
install: "pip install pycroscopy"
# command to run tests
script: pytest